name: Download Integration Test

on:
  workflow_run:
    workflows: [ "Build Apptainer Image" ]
    types:
      - completed

jobs:
  download-integration-test:
    # Only run if the Apptainer image build succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/apptainer/apptainer:latest
      options: --privileged
    env:
      DOWNLOAD_INTEGRATION_TEST_START_DATETIME: '2001-01-01T00:00:00'
      DOWNLOAD_INTEGRATION_TEST_END_DATETIME: '2001-01-02T00:00:00'
    steps:
      - uses: actions/checkout@v6

      - name: Log in to the container registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u ${{ github.repository_owner }} --password-stdin oras://ghcr.io

      - name: Pull the Apptainer image built by the previous workflow
        run: |
          repo=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          apptainer pull container.sif oras://ghcr.io/${repo}:${tag}

      # Pull the latest config from the arco-ocean repo so the output is checked against it
      - name: Download configuration file
        uses: actions/checkout@v6
        with:
          repository: inogs/arco-ocean
          path: arco-ocean
          sparse-checkout: configs/arco-ocean_tres-1d_res-0p25_levels-10.toml
          sparse-checkout-cone-mode: false

      - name: Run download integration test
        env:
          COPERNICUSMARINE_SERVICE_USERNAME: ${{ secrets.COPERNICUSMARINE_SERVICE_USERNAME }}
          COPERNICUSMARINE_SERVICE_PASSWORD: ${{ secrets.COPERNICUSMARINE_SERVICE_PASSWORD }}
          CDSAPI_URL: ${{ secrets.CDSAPI_URL }}
          CDSAPI_KEY: ${{ secrets.CDSAPI_KEY }}
        run: >
          apptainer run container.sif arco-make download
          --start=${DOWNLOAD_INTEGRATION_TEST_START_DATETIME} --end=${DOWNLOAD_INTEGRATION_TEST_END_DATETIME}
          --no-progress
          --overwrite
          --
          arco-ocean/configs/arco-ocean_tres-1d_res-0p25_levels-10.toml /tmp/tempfile.zip

      - name: Verify output
        run: |
          ls -l /tmp/tempfile.zip
#          apptainer exec container.sif python tests/integration/check_download.py \
#            /tmp/tempfile.zip \
#            --start=${DOWNLOAD_INTEGRATION_TEST_START_DATETIME} --end=${DOWNLOAD_INTEGRATION_TEST_END_DATETIME}
